const data = [
    {
        id: 'house1',
        title: '10 BHK Independent House For Sale in Noida, UP',
        description: 'The Property is fully Built Up And Comprises of Basement,Ground Floor, First Floor, Second Floor and Third Floor with Open Terrace. Each Floor has 3 bedrooms with attach washrooms, Drawing Room, Modular Kitchen, The building also has Lift Facility.',
        image: './images/house1.webp',
        type: 'house',
        location: 'Noida',
        price: 4000000,
        priceRange: '>10L',
        moveDate: '2023-01-01'
    },
    {
        id: 'house2',
        title: '4 BHK Independent House For Sale in New Delhi',
        description: '4 BHK Independent House for sale in Delhi. This property is in Nawada, which is a coveted investment location. This tastefully designed 4 BHK unit is among the best properties. Contact now for more details.',
        image: './images/house2.webp',
        type: 'house',
        location: 'New Delhi',
        price: 2000000,
        priceRange: '>10L',
        moveDate: '2022-09-01'
    },
    {
        id: 'house3',
        title: '5 BHK Independent House For Sale in Gurgaon, Haryana',
        description: '5 BHK Independent House for sale in Gurgaon. Liveable kothi available for sale in one of the best localities of vikaspuri....park facing location...contact for further details',
        image: './images/house3.webp',
        type: 'house',
        location: 'Gurgaon',
        price: 900000,
        priceRange: '6L-10L',
        moveDate: '2022-10-01'
    },
    {
        id: 'house4',
        title: '3 BHK Independent House For Sale in Alwar, Rajasthan',
        description: '3 BHK Independent House for sale in Alwar, Rajasthan. Best deal for such a good house. Contact me for more details.',
        image: './images/house4.webp',
        type: 'house',
        location: 'Alwar',
        price: 2200000,
        priceRange: '>10L',
        moveDate: '2022-09-01'
    },
    {
        id: 'land1',
        title: 'Residential Plot in Alwar, Rajasthan',
        description: 'New land booking now... in Alwar, Rajasthan. Best deal for such a plot. Contact me for more details.',
        image: './images/land1.webp',
        type: 'land',
        location: 'Alwar',
        price: 220000,
        priceRange: '0L-3L',
        moveDate: '2022-09-01'
    },
    {
        id: 'land2',
        title: 'DDA Residential Plots, Sector 19 Dwarka, New Delhi',
        description: '210 Square meters Plot for sale in Sector 19, Dwarka, Delhi. This land has a dimension of 10.0 mt length 17.0 mt width.',
        image: './images/land2.webp',
        type: 'land',
        location: 'New Delhi',
        price: 850000,
        priceRange: '6L-10L',
        moveDate: '2022-12-01'
    },
    {
        id: 'land3',
        title: 'Residential Plot in Noida, UP',
        description: '28 Square meters Plot for sale in Noida, UP. This land has a dimension of 4.0 mt length 7.0 mt width.',
        image: './images/land3.webp',
        type: 'land',
        location: 'Noida',
        price: 350000,
        priceRange: '3L-6L',
        moveDate: '2023-01-01'
    },
    {
        id: 'land4',
        title: 'Residential Plot in Gurgaon, Haryana',
        description: '60 Square meters Plot for sale in Gurgaon, Haryana. This land has a dimension of 12.0 mt length 5.0 mt width.',
        image: './images/land4.webp',
        type: 'land',
        location: 'Gurgaon',
        price: 460000,
        priceRange: '3L-6L',
        moveDate: '2022-09-01'
    },
    {
        id: 'house5',
        title: '11 BHK Independent House For Sale in Gurgaon, Haryana',
        description: 'The Property is fully Built Up And Comprises of Basement,Ground Floor, First Floor, Second Floor and Third Floor with Open Terrace. Each Floor has 3 bedrooms with attach washrooms, Drawing Room, Modular Kitchen, The building also has Lift Facility.',
        image: './images/house1.webp',
        type: 'house',
        location: 'Gurgaon',
        price: 4200000,
        priceRange: '>10L',
        moveDate: '2022-11-01'
    },
    {
        id: 'house6',
        title: '2 BHK Independent House For Sale in Rohini, New Delhi',
        description: '2 BHK Independent House for sale in Rohini, New Delhi. Liveable kothi available for sale in one of the best localities of vikaspuri....park facing location...contact for further details',
        image: './images/house3.webp',
        type: 'house',
        location: 'New Delhi',
        price: 550000,
        priceRange: '3L-6L',
        moveDate: '2022-10-01'
    },
    {
        id: 'house7',
        title: '3 BHK Independent House For Sale in Noida, UP',
        description: '3 BHK Independent House for sale in Noida. Liveable kothi available for sale in one of the best localities of ghaziabad....park facing location...contact for further details',
        image: './images/house3.webp',
        type: 'house',
        location: 'Noida',
        price: 450000,
        priceRange: '3L-6L',
        moveDate: '2022-11-01'
    },
    {
        id: 'house8',
        title: '4 BHK Independent House For Sale in Alwar, Rajasthan',
        description: '4 BHK Independent House for sale in Alwar, Rajasthan. This property is in Alwar, which is a coveted investment location. This tastefully designed 4 BHK unit is among the best properties. Contact now for more details.',
        image: './images/house2.webp',
        type: 'house',
        location: 'Alwar',
        price: 900000,
        priceRange: '6L-10L',
        moveDate: '2022-10-01'
    },
    {
        id: 'land5',
        title: 'Residential Plot in Malviya Nagar, New Delhi',
        description: 'New land booking now... in Malviya Nagar, New Delhi. Best deal for such a plot. Contact me for more details.',
        image: './images/land1.webp',
        type: 'land',
        location: 'New Delhi',
        price: 550000,
        priceRange: '3L-6L',
        moveDate: '2022-09-01'
    },
    {
        id: 'land6',
        title: 'DDA Residential Plots, Alwar, Rajasthan',
        description: '210 Square meters Plot for sale in Sector 19, Alwar. This land has a dimension of 10.0 mt length 17.0 mt width.',
        image: './images/land2.webp',
        type: 'land',
        location: 'Alwar',
        price: 850000,
        priceRange: '6L-10L',
        moveDate: '2022-09-23'
    },
    {
        id: 'land7',
        title: 'Residential Plot in Gurgaon, Haryana',
        description: '28 Square meters Plot for sale in Gurgaon, Haryana. This land has a dimension of 4.0 mt length 7.0 mt width.',
        image: './images/land3.webp',
        type: 'land',
        location: 'Gurgaon',
        price: 350000,
        priceRange: '3L-6L',
        moveDate: '2022-11-01'
    },
    {
        id: 'land8',
        title: 'Residential Plot in Noida, UP',
        description: '60 Square meters Plot for sale in Noida, UP. This land has a dimension of 12.0 mt length 5.0 mt width.',
        image: './images/land4.webp',
        type: 'land',
        location: 'Noida',
        price: 760000,
        priceRange: '6L-10L',
        moveDate: '2022-09-01'
    },
    {
        id: 'comm1',
        title: 'Office Space, Sector-12, Dwarka, New Delhi',
        description: 'Available for sale is a commercial space situated at Sector 12 Dwarka, a well-known neighbourhood in New Delhi. The propertys age is 10 years.',
        image: './images/comm1.webp',
        type: 'ind/comm',
        location: 'New Delhi',
        price: 250000,
        priceRange: '0L-3L',
        moveDate: '2022-10-01'
    },
    {
        id: 'comm2',
        title: '225 sq.ft Shop, Gurgaon, Haryana',
        description: 'This modern Shop designed with luxury facilities in the heart of New Delhi at Uttam Nagar is an ideal investment option.',
        image: './images/comm2.webp',
        type: 'ind/comm',
        location: 'Gurgaon',
        price: 150000,
        priceRange: '0L-3L',
        moveDate: '2022-11-01'
    },
    {
        id: 'ind1',
        title: 'Industrial Land For Sale in Noida, UP',
        description: 'Deals in Bawana and Bhorgarh industrial area 100 mtr., 150mtr. 200mtr. 250mtr. building and plots available for sale, purchase and rent purpose.',
        image: './images/ind1.jpg',
        type: 'ind/comm',
        location: 'Noida',
        price: 750000,
        priceRange: '6L-10L',
        moveDate: '2022-10-01'
    },
    {
        id: 'ind2',
        title: 'Industrial Land For Sale in Alwar, Rajasthan',
        description: 'The property is Right next to NH44. Industrial area 100 mtr., 150mtr. 200mtr. 250mtr. building and plots available for sale, purchase and rent purpose.',
        image: './images/ind2.jpg',
        type: 'ind/comm',
        location: 'Alwar',
        price: 1050000,
        priceRange: '>10L',
        moveDate: '2023-01-01'
    },
    {
        id: 'agr5',
        title: 'Agricultural Land For Sale in Noida, UP',
        description: '25000 Square feet agricultural land for sale in Valley View Estate, Noida. This farm land has a dimension of 300.0 mt length and 98.0 mt width.',
        image: './images/agr1.webp',
        type: 'agricultural',
        location: 'Noida',
        price: 700000,
        priceRange: '3L-6L',
        moveDate: '2022-09-16'
    },
    {
        id: 'agr6',
        title: 'Agricultural Land For Sale in Rohini, New Delhi',
        description: '6000 Square feet agricultural land for sale in, Rohini New Delhi. This land has a dimension of 12.0 mt length 5.0 mt width.',
        image: './images/agr2.webp',
        type: 'agricultural',
        location: 'New Delhi',
        price: 750000,
        priceRange: '6L-10L',
        moveDate: '2022-10-10'
    },
    {
        id: 'agr7',
        title: 'Agricultural Land For Sale in Gurgaon, Haryana',
        description: '5000 Square feet agricultural land for sale in, Gurgaon, Haryana. This land has a dimension of 60 MTR PLOT . 9 MTR ROAD . POCKET C2',
        image: './images/agr3.webp',
        type: 'agricultural',
        location: 'Gurgaon',
        price: 1500000,
        priceRange: '>10L',
        moveDate: '2022-11-01'
    },
    {
        id: 'agr8',
        title: 'Agricultural Land For Sale in Alwar, Rajasthan',
        description: '6000 Square feet agricultural land for sale in, Alwar, Rajasthan. This land has a dimension of 12.0 mt length 5.0 mt width.',
        image: './images/agr4.webp',
        type: 'agricultural',
        location: 'Alwar',
        price: 200000,
        priceRange: '0L-3L',
        moveDate: '2022-10-01'
    },
    {
        id: 'comm3',
        title: '225 sq.ft Shop, Gurgaon, Haryana',
        description: 'This modern Shop designed with luxury facilities in the heart of New Delhi at Uttam Nagar is an ideal investment option.',
        image: './images/comm1.webp',
        type: 'ind/comm',
        location: 'Gurgaon',
        price: 450000,
        priceRange: '3L-6L',
        moveDate: '2022-09-11'
    },
    {
        id: 'comm4',
        title: 'Office Space, Sector-12, Dwarka, New Delhi',
        description: 'Available for sale is a commercial space situated at Sector 12 Dwarka, a well-known neighbourhood in New Delhi. The propertys age is 10 years.',
        image: './images/comm2.webp',
        type: 'ind/comm',
        location: 'New Delhi',
        price: 950000,
        priceRange: '6L-10L',
        moveDate: '2022-09-18'
    },
    {
        id: 'ind3',
        title: 'Industrial Land For Sale in Alwar, Rajasthan',
        description: 'Deals in Bawana and Bhorgarh industrial area 100 mtr., 150mtr. 200mtr. 250mtr. building and plots available for sale, purchase and rent purpose.',
        image: './images/ind1.jpg',
        type: 'ind/comm',
        location: 'Alwar',
        price: 750000,
        priceRange: '6L-10L',
        moveDate: '2022-10-01'
    },
    {
        id: 'ind4',
        title: 'Industrial Land For Sale in Noida, UP',
        description: 'The property is Right next to NH44. Industrial area 100 mtr., 150mtr. 200mtr. 250mtr. building and plots available for sale, purchase and rent purpose.',
        image: './images/ind2.jpg',
        type: 'ind/comm',
        location: 'Noida',
        price: 450000,
        priceRange: '3L-6L',
        moveDate: '2022-09-01'
    },
    {
        id: 'agr1',
        title: 'Agricultural Land For Sale in Noida, UP',
        description: '25000 Square feet agricultural land for sale in Valley View Estate, Noida. This farm land has a dimension of 300.0 mt length and 98.0 mt width.',
        image: './images/agr1.webp',
        type: 'agricultural',
        location: 'Noida',
        price: 800000,
        priceRange: '6L-10L',
        moveDate: '2022-10-06'
    },
    {
        id: 'agr2',
        title: 'Agricultural Land For Sale in Rohini, New Delhi',
        description: '6000 Square feet agricultural land for sale in, Rohini New Delhi. This land has a dimension of 12.0 mt length 5.0 mt width.',
        image: './images/agr2.webp',
        type: 'agricultural',
        location: 'New Delhi',
        price: 250000,
        priceRange: '0L-3L',
        moveDate: '2022-09-10'
    },
    {
        id: 'agr3',
        title: 'Agricultural Land For Sale in Gurgaon, Haryana',
        description: '5000 Square feet agricultural land for sale in, Gurgaon, Haryana. This land has a dimension of 60 MTR PLOT . 9 MTR ROAD . POCKET C2',
        image: './images/agr3.webp',
        type: 'agricultural',
        location: 'Gurgaon',
        price: 450000,
        priceRange: '3L-6L',
        moveDate: '2022-09-01'
    },
    {
        id: 'agr4',
        title: 'Agricultural Land For Sale in Alwar, Rajasthan',
        description: '6000 Square feet agricultural land for sale in, Alwar, Rajasthan. This land has a dimension of 12.0 mt length 5.0 mt width.',
        image: './images/agr4.webp',
        type: 'agricultural',
        location: 'Alwar',
        price: 700000,
        priceRange: '6L-10L',
        moveDate: '2022-11-01'
    }
];

export default data;